### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dawo5010** [AY1920S1-CS2103T-T13-3/main#364]
- [x] Undo/Redo for DG 
- [x] Check configuration file options
- [x] Add Manual Testing instructions in DG
